export const ItemsSet2 = [
    {
        _id: 1,
        location: 'inventory',
        top: 0,
        left: 0,
        color: 'black',
        amount: 1,
        hideSourceOnDrag: false,
        style: 'triangle',
    },
    {
        _id: 2,
        location: 'inventory',
        top: 0,
        left: 0,
        color: 'white',
        amount: 1,
        hideSourceOnDrag: false,
        style: 'dice',
    },
    {
        _id: 3,
        location: 'inventory',
        top: 0,
        left: 0,
        color: 'white',
        amount: 1,
        hideSourceOnDrag: false,
        style: 'circle',
    },
    {
        _id: 4,
        location: 'inventory',
        top: 0,
        left: 0,
        color: 'white',
        amount: 1,
        hideSourceOnDrag: false,
        style: 'rectangle',
    },
    {
        _id: 5,
        location: 'inventory',
        top: 0,
        left: 0,
        color: 'white',
        amount: 1,
        hideSourceOnDrag: false,
        style: 'thinrectangle',
    },
    {
        _id: 6,
        location: 'inventory',
        top: 0,
        left: 0,
        color: 'white',
        amount: 1,
        hideSourceOnDrag: false,
        style: 'bridge',
    }
]